import {StyleSheet} from 'react-native';
import {screenWidth} from '../screens/MarvelHeroes';

export const styles = StyleSheet.create({
  notFoundText: {
    fontFamily: 'Marvel-Regular',
    fontSize: 20,
  },
  notFoundContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  clearInput: {
    height: 50,
    width: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputsearch: {
    width: '80%',
    paddingLeft: 15,
    borderRadius: 45,
    borderColor: 'black',
    borderWidth: 1.5,
    height: 50,
    fontSize: 18,
    backgroundColor: '#fff',
  },
  containerS: {
    margin: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignContent: 'center',
    padding: 10,
  },
  buttonSearch: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mainLabel: {
    fontFamily: 'AvengeanceHeroicAvengerBoldItalic',
    fontSize: 30,
    color: '#fff',
  },
  listContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: '#E21320',
    width: '100%',
    padding: 5,
  },
  searchContainerInternal: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#E21320',
    padding: 10,
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    backgroundColor: '#E21320',
  },
  heroName: {
    fontFamily: 'Marvel-Regular',
    fontSize: 20,
  },
  wrapper: {
    width: '50%',
  },
  miniImg: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#000',
  },
  container: {
    width: 100,
    marginLeft: 30,
  },
  card: {
    backgroundColor: 'white',
    elevation: 2,
    borderWidth: 1.5,
    borderRadius: 10,
    borderColor: '#000',
    margin: 5,
    height: 120,
    width: screenWidth - 40,
    justifyContent: 'space-between',
    alignContent: 'space-around',
    alignItems: 'center',
    flexDirection: 'row',
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 32,
    borderRadius: 45,
    elevation: 3,
    backgroundColor: 'black',
  },
  text: {
    fontSize: 16,
    lineHeight: 21,
    letterSpacing: 0.25,
    color: 'white',
    fontFamily: 'Marvel-Regular',
  },
});
